version: "3.9"

services:
  # PostgreSQL container with connection pooling
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: booking_platform_1
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "Vijay2799#"
      # PostgreSQL tuning for better performance
      POSTGRES_MAX_CONNECTIONS: "200"
      POSTGRES_SHARED_BUFFERS: "256MB"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d booking_platform_1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Redis for caching and Celery broker
  redis:
    image: redis:7.0
    container_name: redis_broker
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    environment:
      - REDIS_PASSWORD=redis_password_123
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password_123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Elasticsearch container
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10

  # Django/DRF application container with Gunicorn
  web:
    build: .
    container_name: booking_platform_web
    command: gunicorn booking_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      SECRET_KEY: "Your-Secret-Key-Here"
      DEBUG: "1"
      DB_NAME: "booking_platform_1"
      DB_USER: "myuser"
      DB_PASSWORD: "Vijay2799#"
      DB_HOST: "db"
      DB_PORT: "5432"
      CELERY_BROKER_URL: "redis://:redis_password_123@redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://:redis_password_123@redis:6379/0"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      DB_CONN_MAX_AGE: "300"
      DB_POOL_SIZE: "20"

  # Celery worker container
  celery:
    build: .
    container_name: django_celery
    command: celery -A booking_platform worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      SECRET_KEY: "Your-Secret-Key-Here"
      DEBUG: "1"
      DB_NAME: "booking_platform_1"
      DB_USER: "myuser"
      DB_PASSWORD: "Vijay2799#"
      DB_HOST: "db"
      DB_PORT: "5432"
      CELERY_BROKER_URL: "redis://:redis_password_123@redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://:redis_password_123@redis:6379/0"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  # Celery Beat for scheduled tasks
  celery-beat:
    build: .
    container_name: django_celery_beat
    command: celery -A booking_platform beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      SECRET_KEY: "Your-Secret-Key-Here"
      DEBUG: "1"
      DB_NAME: "booking_platform_1"
      DB_USER: "myuser"
      DB_PASSWORD: "Vijay2799#"
      DB_HOST: "db"
      DB_PORT: "5432"
      CELERY_BROKER_URL: "redis://:redis_password_123@redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://:redis_password_123@redis:6379/0"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

volumes:
  pg_data:
  redis_data:
  es_data:
