# Generated by Django 5.0.7 on 2025-01-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_booking_date_alter_booking_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="availability",
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.booking",
            ),
        ),
        migrations.CreateModel(
            name="ServiceProviderAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="core.serviceprovider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.serviceprovideravailability",
            ),
        ),
    ]
