# Generated by Django 5.0.7 on 2025-02-01 07:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_booking_confirmation_sent_booking_reminder_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
