# Generated by Django 5.0.7 on 2025-02-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_booking_duration_booking_total_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["appointment_time"]},
        ),
    ]
